### PR TITLE
🐛 Next.js Bugs - Fix `useLocation` + Custom Hook

### LINKED ISSUE #66: 🐛 Bug - Next.js Issues
Currently, there are a couple issues with the `ssw.megamenu` package when used with the v3 site:

* Issue with the `react-use` package, where there is some sort of conflict with ESM
image
**Figure: broken when importing `ssw.megamenu@4.1.0`**

* When editing megamenu using Tina, a `useEffect` fires every time that replaces the edited Tina data with API data

MicrosoftTeams-image (6)

```[tasklist]
### Tasks
- [ ] Fix the reference to the `useLocation` hook 
- [ ] Fix rerendering issue, as when you edit it on TinaCMS, it does not use the data passed to the component from TinaCMS, instead fetches data from the API route
```

### PR DESCRIPTION
**Pull request by Harry-Ross**
Fixes #66 

* Removed `react-use` dependency, replaced with the `searchUrl` prop
* Fixed `useMenuItems` to render Tina data as its being edited 
* Made external module discovery automatic from `package.json` instead of external modules being manually added in `vite.config.ts` - reduction in bundle size in `index.js` from 92.4 kb to 31.07 kb

### CODE REVIEW

File: lib/components/CountryDropdown/CountryDropdown.tsx [hunk 1]
```diff
@@ -22,17 +21,28 @@ const websites: { country: Countries; url: string }[] = [
...
+const CountryDropdown = ({ url }: CountryDropdownProps) => {
   const [isOpened, setIsOpened] = useState(false);
   const [currentCountry, setCurrentCountry] = useState<Countries>("Australia");
 
   useEffect(() => {
-    const website = websites.find((w) => host?.endsWith(w.url));
-    if (website) {
-      setCurrentCountry(website.country);
+    try {
+      console.log("url", url);
```
Comment (JackDevAU) [inline lib/components/CountryDropdown/CountryDropdown.tsx:34]: Remove logs ;)

**Review by JackDevAU — APPROVED** [review]
lgtm
